export const CHANGE_MERCHANT = 'CHANGE_MERCHANT';
export const SET_MERCHANTS = 'SET_MERCHANTS';
export const FETCH_MERCHANTS = 'FETCH_MERCHANTS';

export const CHANGE_LOCATION = 'CHANGE_LOCATION';
export const ADD_LOCATIONS = 'ADD_LOCATIONS';
export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';

export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_USER = 'SET_USER';
export const FETCH_USER = 'FETCH_USER';

export const SET_DAY_COUNT = 'SET_DAY_COUNT';

export const CHANGE_GRAPH_DISPLAY_TYPE = 'CHANGE_GRAPH_DISPLAY_TYPE';
export const SET_GRAPH_DATA = 'SET_GRAPH_DATA';
export const CHANGE_GRAPH_DATE_RANGE = 'CHANGE_GRAPH_DATE_RANGE';
export const CHANGE_GRAPH_DISPLAY_OPTION = 'CHANGE_GRAPH_DISPLAY_OPTION';

export const SHOW_OVERLAY = 'SHOW_OVERLAY';
export const HIDE_OVERLAY = 'HIDE_OVERLAY';

export const CHANGE_ENTRIES_FROM = 'CHANGE_ENTRIES_FROM';
export const CHANGE_ENTRIES_TO = 'CHANGE_ENTRIES_TO';
export const ADD_ENTRIES = 'ADD_ENTRIES';
