export const CHANGE_MERCHANT = 'CHANGE_MERCHANT';

export const CHANGE_LOCATION = 'CHANGE_LOCATION';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGIN_USER = 'LOGIN_USER';


export const SET_DAY_COUNT = 'SET_DAY_COUNT';

export const CHANGE_GRAPH_DISPLAY_TYPE = 'CHANGE_GRAPH_DISPLAY_TYPE';
export const SET_GRAPH_DATA = 'SET_GRAPH_DATA';
export const CHANGE_GRAPH_DATE_RANGE = 'CHANGE_GRAPH_DATE_RANGE';
export const CHANGE_GRAPH_DISPLAY_OPTION = 'CHANGE_GRAPH_DISPLAY_OPTION';

